spring:
  application:
    name: sermao

datasource:
  url: ${DATASOURCE_URL}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driver-class-name: org.postgresql.Driver
   
server:
  servlet:
    context-path: /sermao-manager/api